name: ts_core
description: core to use inside app
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  bloc: ^8.1.0
  cloud_firestore: ^4.3.1
  cloud_firestore_platform_interface: ^5.10.1
  cloud_firestore_web: ^3.2.1
  collection: ^1.17.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3
  firebase_analytics: ^10.0.6
  firebase_analytics_web: ^0.5.1+5
  firebase_auth: ^4.2.5
  firebase_auth_platform_interface: ^6.11.7
  firebase_auth_web: ^5.2.4
  firebase_core: ^2.3.0
  firebase_core_web: ^2.0.1
  firebase_crashlytics: ^3.0.6
  firebase_dynamic_links: ^5.0.11
  firebase_ui_auth: ^1.1.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  flutter_keyboard_visibility: ^5.2.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  jwt_decoder: ^2.0.1
  life_hooks: ^0.0.18
  logger: ^1.1.0
  office_addin_helper: ^0.3.0
  officejs: ^0.3.1
  path_to_regexp: ^0.4.0
  provider: ^6.0.4
  quiver: ^3.1.0
  retrofit: ^3.3.1
  russian_words: ^0.2.0
  shared_preferences: ^2.0.15
  ts_design_core:
    path: ../ts_design_core
  universal_io: ^2.0.4
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.3.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  retrofit_generator: ^4.2.0
  xsoulspace_lints: ^0.0.5

dependency_overrides:
  officejs:
    path: ../../../officejs_dart
  office_addin_helper:
    path: ../../../office_addin_helper
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
# assets:
#   - assets/images/
# fonts:
#   - family: asgard_icons
#     fonts:
#       - asset: packages/la_design_core/fonts/asgard_icons.ttf
#   - family: Poppins
#     fonts:
#       - asset: packages/la_design_core/fonts/Poppins-Regular.ttf
#         weight: 400
#       - asset: packages/la_design_core/fonts/Poppins-Bold.ttf
#         weight: 700
flutter_intl:
  enabled: true
